import { pgTable, text, integer, timestamp, boolean } from "drizzle-orm/pg-core";
export const splMatchesTable = pgTable("spl_matches", {
    id: text("id").primaryKey(),
    team1Id: text("team1_id").notNull(),
    team2Id: text("team2_id").notNull(),
    venue: text("venue").notNull().default(""),
    matchDate: text("match_date"),
    overs: integer("overs").notNull().default(20),
    status: text("status").notNull().default("upcoming"),
    winnerId: text("winner_id"),
    tossWinnerId: text("toss_winner_id"),
    tossDecision: text("toss_decision"),
    youtubeUrl: text("youtube_url"),
    createdAt: timestamp("created_at", { mode: "string" }).notNull().defaultNow(),
});
export const splInningsTable = pgTable("spl_innings", {
    id: text("id").primaryKey(),
    matchId: text("match_id").notNull(),
    inningsNumber: integer("innings_number").notNull(),
    battingTeamId: text("batting_team_id").notNull(),
    bowlingTeamId: text("bowling_team_id").notNull(),
    totalRuns: integer("total_runs").notNull().default(0),
    totalWickets: integer("total_wickets").notNull().default(0),
    oversCompleted: integer("overs_completed").notNull().default(0),
    ballsCurrentOver: integer("balls_current_over").notNull().default(0),
    target: integer("target"),
    status: text("status").notNull().default("in_progress"),
    currentStrikerId: text("current_striker_id"),
    currentNonStrikerId: text("current_non_striker_id"),
    currentBowlerId: text("current_bowler_id"),
    createdAt: timestamp("created_at", { mode: "string" }).notNull().defaultNow(),
});
export const splBallsTable = pgTable("spl_balls", {
    id: text("id").primaryKey(),
    inningsId: text("innings_id").notNull(),
    overNumber: integer("over_number").notNull(),
    ballInOver: integer("ball_in_over").notNull(),
    batsmanId: text("batsman_id").notNull(),
    bowlerId: text("bowler_id").notNull(),
    runsOffBat: integer("runs_off_bat").notNull().default(0),
    extras: integer("extras").notNull().default(0),
    extrasType: text("extras_type").notNull().default("none"),
    isWicket: boolean("is_wicket").notNull().default(false),
    wicketType: text("wicket_type"),
    fielderId: text("fielder_id"),
    isLegal: boolean("is_legal").notNull().default(true),
    createdAt: timestamp("created_at", { mode: "string" }).notNull().defaultNow(),
});
